---
- block:
  - git:
      repo: 'https://github.com/UedaTakeyuki/mh-z19.git'
      dest: ~/mh-z19

  # - name: Run setup
    # shell: "{{ ansible_env.HOME }}/mh-z19/setup.sh"
    # become: yes

  - name: Install sensor module
    become: yes
    pip: 
      name: 
        - mh-z19

  - name: Install jq
    apt:
      name: jq
      state: latest
    become: yes

  - name: Copy cron script
    become: yes
    copy:
      src: get-concentration.sh
      dest: "{{ ansible_env.HOME }}/get-concentration.sh"
      mode: '0755'

  - name: Get co2 concentration
    become: yes
    cron:
      name: 'get co2 concentration'
      minute: 1
      job: "{{ ansible_env.HOME }}/get-concentration.sh"

  tags: co2-detection
