---
- block:
  - git:
      repo: 'https://github.com/UedaTakeyuki/mh-z19.git'
      dest: ~/mh-z19

  # - name: Run setup
    # shell: "{{ ansible_env.HOME }}/mh-z19/setup.sh"
    # become: yes

  - name: Install sensor module
    become: yes
    pip: 
      name: 
        - mh-z19

  - name: Install jq
    apt:
      name: jq
      state: latest
    become: yes

  - name: Copy cron script
    copy:
      src: get-concentration.sh
      dest: "{{ ansible_env.HOME }}/get-concentration.sh"
      mode: '0755'

  - name: Copy set-sudoers file
    copy:
      src: set-sudoers.sh
      dest: "{{ ansible_env.HOME }}/set-sudoers.sh"
      mode: '0755'

  - name: Run set-sudoers
    shell: "{{ ansible_env.HOME }}/set-sudoers.sh"

  - name: Create cron log dir
    file:
      path: ~/cron
      state: directory
      mode: '0755'

  - name: Get co2 concentration
    cron:
      name: 'get co2 concentration'
      job: "{{ ansible_env.HOME }}/get-concentration.sh 1>~/cron/exec.log 2>~/cron/err.log"

  tags: co2-detection
